### ISSUE TITLE
Css 

### ISSUE THREAD

**Issue by Mekuna** [Yntymak-ja/SECTION#3]
видеону коруп,код жазуу

**Comment by Orgument** [comment]
<b> тег калып калды

**Comment by Mekuna** [comment]
@Orgument  менде арткы фон иштебей жатат 
<bC>1323

**Comment by Orgument** [comment]
![CSS3_logo_and_wordmark svg](https://user-images.githubusercontent.com/80907971/127781660-f6d70591-34f7-449d-9d01-21b42acafa23.png)

**Comment by Mekuna** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/87778832/127781704-369bed7a-df9b-40b2-bded-230b00504084.png)

**Comment by Mekuna** [comment]
Меники дагы эле ишеген жок
